config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items do
    member do
      get 'purchase',to: 'items#purchase'
      post 'done',to: 'items#done'
     end
  #Ajaxで動くアクションのルート
  collection do
    get 'get_category_children', defaults: { format: 'json' }
    get 'get_category_grandchildren', defaults: { format: 'json' }
  end
  end 
  resources :users, only: [:edit, :update, :show] do
    resources :addresses, only: [:new, :create, :edit, :update]
  end

  resources :cards, only: [:index,:new,:show] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'buy', to: 'cards#buy'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader

  has_many :items
  validates :nickname, :first_name, :last_name, :first_name_kana, :last_name_kana, :birthday, presence: true
  validates :profile, length: { maximum: 250 }

  has_many :cards 
  has_one :address
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  private

  def callback_for(provider)
    @omniauth = request.env['omniauth.auth']
    info = User.find_oauth(@omniauth)
    @user = info[:user]
    if @user.persisted? 
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else 
      @sns = info[:sns]
      render template: "devise/registrations/new" 
    end
  end

  def failure
    redirect_to root_path and return
  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # GET /resource/sign_up
  #1ページ目
  def new
    @user = User.new
  end

  # POST /resource
  #1ページ目post
  def create
    session[:nickname] = params[:user][:nickname]
    session[:first_name] = params[:user][:first_name]
    session[:last_name] = params[:user][:last_name]
    session[:first_name_kana] = params[:user][:first_name_kana]
    session[:last_name_kana] = params[:user][:last_name_kana]
    session[:birthday] = birthday_join
    session[:email] = params[:user][:email]
    session[:password] = params[:user][:password]
    # session[:phone_number] = params[:user][:phone_number]
    @user = User.new(
      nickname: session[:nickname],
      first_name: session[:first_name],
      last_name: session[:last_name],
      first_name_kana: session[:first_name_kana],
      last_name_kana: session[:last_name_kana],
      birthday: session[:birthday],
      email: session[:email],
      # phone_number: session[:phone_number]
    )
    #SNSで登録する場合
    if session[:provider].present? && session[:uid].present?
      # パスワードは自動生成する
      password = Devise.friendly_token.first(7)
      @user.password = password
      session[:password] = password
    #メールアドレスで登録する場合
    else
      @user.password = session[:password]
    end
    @phone = @user.phone_number
    # バリデーションチェック
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    render :new_phone
  end

  #2ページ目post
  def create_phone
    @user = User.create(
      nickname: session[:nickname],
      first_name: session[:first_name],
      last_name: session[:last_name],
      first_name_kana: session[:first_name_kana],
      last_name_kana: session[:last_name_kana],
      birthday: session[:birthday],
      email: session[:email],
      password: session[:password]
    )
    @phone = Phone.new(phone_params)
    unless @phone.valid?
      flash.now[:alert] = @phone.errors.full_messages
      render :new_phone and return
    end
    @phone.save
    if session[:provider].present? && session[:uid].present?
      @sns = SnsCredential.create(
        user_id: @user.id,
        uid: session[:uid],
        provider: session[:provider]
      )
    end
    sign_in(:user, @user)
  end

  protected

  def phone_params
    params.require(:user).permit(:phone_number).merge(user_id: @user.id)
  end

  #birthdayのパラメータをData型として生成する。
  def birthday_join
    params[:user][:last_name_kana] = Date.new(
      params[:user]["birthday(1i)"].to_i,
      params[:user]["birthday(2i)"].to_i,
      params[:user]["birthday(3i)"].to_i
    )
  end



end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def edit
    user = User.find(params[:id])
    @image = user.image
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  require "payjp"


  def show
    @user = User.find(params[:id])
    @image = @user.image
    @profile = @user.profile
    @address = Address.select(:user_id)
    @card =Card.find_by(user_id: current_user.id)
  end

  def create
    @user = User.new(post_params)
  end


  private

  def user_params
    params.require(:user).permit(:image, :profile)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_leftside.html.haml
.side
  .mypage-nav
    .mypage-nav__list
      %li.mypage-nav__list-item
        マイページ
      %li.mypage-nav__list-item
        お知らせ
      %li.mypage-nav__list-item
        やることリスト
      %li.mypage-nav__list-item
        いいね！一覧
      %li.mypage-nav__list-item
        出品する
      %li.mypage-nav__list-item
        出品した商品-出品中
      %li.mypage-nav__list-item
        出品した商品-取引中
      %li.mypage-nav__list-item
        出品した商品-売却済み
      %li.mypage-nav__list-item
        購入した商品-取引中
      %li.mypage-nav__list-item
        購入した商品-過去の取引
      %li.mypage-nav__list-item
        ニュース一覧
      %li.mypage-nav__list-item
        評価一覧
      %li.mypage-nav__list-item
        ガイド
      %li.mypage-nav__list-item
        お問い合わせ

    .mypage-nav__head
      ペイメント
    .mypage-nav__list
      %li.mypage-nav__list-item
        売上・振込申請

      %li.mypage-nav__list-item
        ポイント



    .mypage-nav__head
      設定
    .mypage-nav__list
      %li.mypage-nav__list-item
        プロフィール

    .mypage-nav__list
      %li.mypage-nav__list-item
        -# もしユーザーがすでに発送元・お届け先住所(address)を登録済であれば編集画面へ
        -# でなければ新規登録画面へ
        - if @user.address.present?
          = link_to "発送元・お届け先住所変更", edit_user_address_path(@user)
        - else
          = link_to "発送元・お届け先住所変更", new_user_address_path(@user)
    .mypage-nav__list
      %li.mypage-nav__list-item
        -# もしユーザーがすでにクレジットカードを登録済であれば一覧・編集画面へ
        -# でなければ新規登録画面へ
        - if @user.cards.present?
          = link_to "支払い方法", card_path(@user)
        - else
          = link_to "支払い方法", new_card_path
    .mypage-nav__list
      %li.mypage-nav__list-item
        メール/パスワード

    .mypage-nav__list
      %li.mypage-nav__list-item
        本人情報

    .mypage-nav__list
      %li.mypage-nav__list-item
        電話番号の確認

    .mypage-nav__list
      %li.mypage-nav__list-item
        ログアウト

app/views/users/_rightbottommain.html.haml
.mypage
  .mypage--list
    .mypage--list--info
      お知らせ
    .mypage--list--todo
      やることリスト

  .tab--list
    %li.tab--list--info
      お知らせ1
    %li.tab--list--info
      お知らせ2
    %li.tab--list--info
      お知らせ3
    %li.tab--list--info
      お知らせ4
    %li.tab--list--info
      お知らせ5
    .info-go-list
      = link_to "一覧を見る", "#"

    -# .info--list-not-found
    -#   現在お知らせはありません

    


    %li.tab--list--todo
      やるべきこと1
    %li.tab--list--todo
      やるべきこと2
    %li.tab--list--todo
      やるべきこと3
    %li.tab--list--todo
      やるべきこと4
    %li.tab--list--todo
      やるべきこと5
    .todo-go-list
      = link_to "一覧を見る", "#"

    
    -# .todo--list-not-found
    -#   現在やるべきことはありません


.goods
  .goods-name
    購入した商品

  .goods-purchase
    .goods-purchase--transaction
      取引中
    .goods-purchase--post
      過去の取引

  .tab-list
    %li.tab-list--transaction
      取引1
    %li.tab-list--transaction
      取引2
    %li.tab-list--transaction
      取引3
    %li.tab-list--transaction
      取引4
    %li.tab-list--transaction
      取引5
    .transaction-go-list
      = link_to "一覧を見る", "#"

    -# .transaction--list-not-found
    -#   取引中の商品がありません

    
    %li.tab-list--post
      過去購入物1
    %li.tab-list--post
      過去購入物2
    %li.tab-list--post
      過去購入物3
    %li.tab-list--post
      過去購入物4
    %li.tab-list--post
      過去購入物5
    .post-go-list
      = link_to "一覧を見る", "#"

    -# .post--list-not-found
    -#   過去の取引がありません

app/views/users/_righttopmain.html.haml
.user
  .user-image
    .user-icon
      -if @image.present?
        = link_to image_tag(@image.url), edit_user_path
      - else
        = link_to image_tag("default.png", class:"user-icon"), edit_user_path
      

    .user-name
      ユーザー
    .user-mumber
      .user-evaluation
        評価 10
      .user-sell
        出品数 10

    .user-profile
      = simple_format(@profile)
    

  

app/views/users/edit.html.haml
.container
  = render 'items/header'
  .account-page
    = form_for(current_user) do |f|
      //アイコン追加部分
      .account-page__inner--icon
        .account-page__inner--icon__label
        .account-page__inner--icon__input
          - if @image.present?
            = image_tag @image.url, class: 'account-page__inner--icon__input__image', width: '100%'
          - else
            = image_tag("default.png") 
          .account-page__inner--icon__input__image2
          = f.file_field :image, class: 'account-page__inner--icon__input__btn', id: 'upload-icon'

      .account-page__inner--user-form
        //プロフィール追加部分
        .field
          .field-label
            = f.label :プロフィールを入力する
          .field-input
            = f.text_area :profile, autocomplete: 'off'
          .filed-submit
            = f.submit :UPDATE
  = render 'items/footer'

app/views/users/show.html.haml
.container
  = render 'items/header'
  .mypage_main
    .content
      = render "righttopmain"
      = render "rightbottommain"
    = render "leftside"
  = render 'items/footer'