config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items do
    member do
      get 'purchase',to: 'items#purchase'
      post 'done',to: 'items#done'
     end
  #Ajaxで動くアクションのルート
  collection do
    get 'get_category_children', defaults: { format: 'json' }
    get 'get_category_grandchildren', defaults: { format: 'json' }
  end
  end 
  resources :users, only: [:edit, :update, :show] do
    resources :addresses, only: [:new, :create, :edit, :update]
  end

  resources :cards, only: [:index,:new,:show] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'buy', to: 'cards#buy'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
      {id: 1, name:'北海道'}, 
      {id: 2, name:'青森県'},
      {id: 3, name:'岩手県'}, 
      {id: 4, name:'宮城県'}, 
      {id: 5, name:'秋田県'}, 
      {id: 6, name:'山形県'}, 
      {id: 7, name:'福島県'}, 
      {id: 8, name:'茨城県'}, 
      {id: 9, name:'栃木県'}, 
      {id: 10, name:'群馬県'}, 
      {id: 11, name:'埼玉県'}, 
      {id: 12, name:'千葉県'}, 
      {id: 13, name:'東京都'}, 
      {id: 14, name:'神奈川県'}, 
      {id: 15, name:'新潟県'}, 
      {id: 16, name:'富山県'}, 
      {id: 17, name:'石川県'}, 
      {id: 18, name:'福井県'}, 
      {id: 19, name:'山梨県'}, 
      {id: 20, name:'長野県'}, 
      {id: 21, name:'岐阜県'}, 
      {id: 22, name:'静岡県'}, 
      {id: 23, name:'愛知県'}, 
      {id: 24, name:'三重県'}, 
      {id: 25, name:'滋賀県'}, 
      {id: 26, name:'京都府'}, 
      {id: 27, name:'大阪府'}, 
      {id: 28, name:'兵庫県'}, 
      {id: 29, name:'奈良県'}, 
      {id: 30, name:'和歌山県'}, 
      {id: 31, name:'鳥取県'}, 
      {id: 32, name:'島根県'}, 
      {id: 33, name:'岡山県'}, 
      {id: 34, name:'広島県'}, 
      {id: 35, name:'山口県'}, 
      {id: 36, name:'徳島県'}, 
      {id: 37, name:'香川県'}, 
      {id: 38, name:'愛媛県'}, 
      {id: 39, name:'高知県'}, 
      {id: 40, name:'福岡県'}, 
      {id: 41, name:'佐賀県'}, 
      {id: 42, name:'長崎県'}, 
      {id: 43, name:'熊本県'}, 
      {id: 44, name:'大分県'}, 
      {id: 45, name:'宮崎県'}, 
      {id: 46, name:'鹿児島県'}, 
      {id: 47, name:'沖縄県'}, 
  ]
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
end

app/models/delivery_charge.rb
class DeliveryCharge < ActiveHash::Base
  self.data = [
      {id: 1, name: '送料込み(出品者負担)'},
      {id: 2, name: '着払い(購入者負担)'},
  ]
end

app/models/item.rb
class Item < ApplicationRecord

  #active_hash
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :status
  belongs_to_active_hash :delivery_charge
  belongs_to_active_hash :shipping_date
  belongs_to_active_hash :area


  #Association
  belongs_to :user
  has_many :comments
  has_many :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures, allow_destroy: true
  belongs_to :category

  #validation
  validates :price,:status,:delivery_charge_id,:area_id,:shipping_date_id, presence: true
  validates :item_name, presence: true, length: {maximum: 40}
  validates :discription, presence: true, length: {maximum: 1000}

  validates_associated :pictures
  validates :pictures, presence: true
  
  
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader

  #Association
  belongs_to :item
  validates :image, presence: true
end

app/models/shipping_date.rb
class ShippingDate < ActiveHash::Base
  self.data = [
      {id: 1, name: '1~2日で発送'},
      {id: 2, name: '2~3日で発送'},
      {id: 3, name: '4~7日で発送'},
  ]
end

app/models/shipping_method.rb
class ShippingMethod < ActiveHash::Base
  self.data = [
    {id: 1, name: "ゆうメール"},
    {id: 2, name: "ゆうパケット"},
    {id: 3, name: "クリックポスト"},
    {id: 4, name: "ゆうパック"},
    {id: 5, name: "宅急便"},
    {id: 6, name: "普通郵便"},
    {id: 7, name: "レターパック"},
    {id: 8, name: "ゆうゆうフリマ便"},
    {id: 9, name: "らくらくフリマ便"},
  ]
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
      {id: 1, name: '新品、未使用'},
      {id: 2, name: '未使用に近い'},
      {id: 3, name: '目立った傷や汚れなし'},
      {id: 4, name: 'やや傷や汚れあり'},
      {id: 5, name: '傷や汚れあり'},
      {id: 6, name: '全体的に状態が悪い'},
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader

  has_many :items
  validates :nickname, :first_name, :last_name, :first_name_kana, :last_name_kana, :birthday, presence: true
  validates :profile, length: { maximum: 250 }

  has_many :cards 
  has_one :address
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only: [:edit, :show]  

  def index
    @item = Item.all.order("created_at DESC").limit(3)
    @items = Item.includes(:pictures).order('created_at DESC')
    @picture = Picture.all
  end

  def new
    @item = Item.new
    @item.pictures.new
    #セレクトボックスの初期値設定
    # @category_parent = Category.where(ancestry: nil)
  end

  # 以下全て、formatはjsonのみ
  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(id: "#{params[:parent_name]}", ancestry: nil).children
  end
  
  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def create
    @item = Item.new(item_params)
      if @item.save
        redirect_to root_path,notice: '商品の出品が完了しました'
      else
        @item.pictures.new
        render "new"
      end
  end


  def show
  end

  def edit
    @item.pictures.new
  end


  def update
    item = Item.find(params[:id])
    if item.update!(item_params)
      redirect_to root_path, notice: "商品の編集が完了しました"
    else
      render :edit
    end
  end

  def purchase
    @item = Item.find(params[:id])
    @item.pictures.new
    card = Card.find_by(user_id: current_user.id)
    #Cardテーブルは前回記事で作成、テーブルからpayjpの顧客IDを検索
    if card.blank?
      #登録された情報がない場合にカード登録画面に移動
      redirect_to new_card_path(@user)
    else
      Payjp.api_key = "sk_test_1547c1078a795141e2ee8623"
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(card.customer_id)
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def done
    @item = Item.find(params[:id])
    card = Card.find_by(user_id: current_user.id)
    Payjp.api_key = "sk_test_1547c1078a795141e2ee8623"
    Payjp::Charge.create(
      amount: @item.price, 
      customer: card.customer_id, 
      currency: 'jpy',
    )
    @item = Item.update(buyer_id: 1)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to root_path,notice:'商品を削除しました'
  end

  def edit
    @grandchild_category = @item.category
    @child_category = @grandchild_category.parent
  end


  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to root_path, notice: "商品の編集が完了しました"
    else
      render :edit
    end
  end

  def set_item
    @item = Item.find(params[:id])
  end


  private
  def item_params
    params.require(:item).permit(:category_id,:image_cache,:item_name,:brand,:price,:discription,:status_id,:delivery_charge_id,:area_id,:shipping_date_id,:shipping_method_id,pictures_attributes:[:image, :id, :_destroy]).merge(user_id: current_user.id,seller_id:current_user.id)
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_error_messages.html.haml
- if @item.errors.any? 
  .itemsMain__errors
    %h2= "#{@item.errors.full_messages.count}件のエラーが発生しました。"
    %ul
    - @item.errors.full_messages.each do |message|
      %li= message
  

app/views/items/_footer.html.haml
.footer 
  %ul.footer__menu
    %li.footer-nav
      %h2.footer-nav__header FURIMAについて
      %ul
        %li
          =link_to "会社概要（運営会社）","#" 
        %li
          =link_to "プライバシーポリシー","#"
        %li
          =link_to "FURIMA利用規約","#" 
        %li
          =link_to "ポイントに関する特約","#" 
    %li.footer-nav
      %h2.footer-nav__header FURIMAを見る
      %ul
        %li
          =link_to "カテゴリ一覧","#"
        %li
          =link_to "ブランド一覧", "#" 
    %li.footer-nav
      %h2.footer-nav__header ヘルプ＆ガイド
      %ul
        %li
          =link_to "FURIMAガイド","#" 
        %li
          =link_to "FURIMAロゴ利用ガイドライン", "#"
        %li
          =link_to "お知らせ","#" 
  .footer__logo
    =image_tag "logo-white.png"
    =link_to "" 
    %p © FURIMA 
    =link_to ""
  .Exhibition-Btn
    - if user_signed_in? && current_user
      =link_to new_item_path do
        %span.Exhibition-Btn__text 出品する
        = image_tag "icon_camera.png", class: "Exhibition-Btn__icon"
    - else 
      =link_to user_session_path do
        %span.Exhibition-Btn__text 出品する
        = image_tag "icon_camera.png", class: "Exhibition-Btn__icon"

app/views/items/_header.html.haml
.header
  .header__top
    .header__title
      = link_to root_path do
        = image_tag "logo.png",size: "150x40"
    .header__searchBox
      %form{action: "/jp/search",class:"form"}
        %input{type:"serch",name:"keyword",placeholder:"キーワードから探す",class:"search-box"}
          %button.search__button
            .search__button__icon
              = link_to ""
              = image_tag 'icon-search 1.png'
  .header__bottom
    .header__bottom-left
      .categoryBox
        = link_to categories_path do
          = "カテゴリー"
          = image_tag 'icon_category.png'
          %ul.category1
            - @category_parent.each do |parent|
              %li.parent_list
                = parent.name
                %ul.category2
                  - parent.children.each do |child|
                    %li.child_list
                      =child.name
                      %ul.category3
                        - child.children.each do |grandchild|
                          %li.grandchild_list
                            =grandchild.name
              
        .category
          %ul.categoryIndex
            %li.categoryIndex--item
              = link_to "レディース", "/"
            %li.categoryIndex--item
              = link_to "メンズ", "/"
            %li.categoryIndex--item
              = link_to "ベビー・キッズ", "/"
            %li.categoryIndex--item
              = link_to "インテリア・住まい・小物", "/"
            %li.categoryIndex--item
              = link_to "本・音楽・ゲーム", "/"
            %li.categoryIndex--item
              = link_to "おもちゃ・ホビー・グッズ", "/"
            %li.categoryIndex--item
              = link_to "コスメ・香水・美容", "/"
            %li.categoryIndex--item
              = link_to "家電・スマホ・カメラ", "/"
            %li.categoryIndex--item
              = link_to "スポーツ・レジャー", "/"
            %li.categoryIndex--item
              = link_to "ハンドメイド", "/"
            %li.categoryIndex--item
              = link_to "チケット", "/"
            %li.categoryIndex--item
              = link_to "自動車・オートバイ", "/"
            %li.categoryIndex--item
              = link_to "その他", "/"
      .brand_box
        = image_tag 'icon_brand.png'
        = link_to "ブランド", "/jp/"
    .header__bottom-right
      .user_box
        -# もしユーザーがログインしているかつログインユーザーであればログアウト、マイページ表示
        -# でなければログイン、新規会員登録表示
        - if user_signed_in? && current_user
          = link_to "ログアウト", destroy_user_session_path, method: :delete
          = link_to "マイページ", user_path(current_user)
        - else
          = link_to "ログイン", new_user_session_path, class: 'new_user_buton',type: 'submit'
          = link_to "新規会員登録",new_user_registration_path, class: 'login_button',type: 'submit'

app/views/items/_main.html.haml
.main  
  .content
    .content__subtitle
      %h2.content__heading
        %br/
        人生を変えるフリマアプリ
      %p.content__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br/
        フリマアプリです
      .content__btn
        = link_to "", class: "AppBtn" do
          = image_tag "App_Store_Badge.svg",size: "180x50"
        = link_to "", class: "GooBtn" do
          = image_tag "google-play-badge.svg",size: "180x50"
  .Explanation
    %h2.subtitle
      FURIMAが選ばれる3つの理由
    %ul.lists
      %li.list
        .list__pict
          %span.number 1
          = image_tag "pict-reason-01.jpg",size:"300x300"
        %h3.list__text
          %span 3分
          ですぐに出品
        %p.list__description
          スマホで入力するだけで簡単に出品できる！
      %li.list
        .list__pict
          %span.number 2
          = image_tag 'pict-reason-02.jpg',size:"300x300"
        %h3.list__text
          %span シンプル
          で使いやすい
        %p.list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.list.list--last
        .list__pict
          %span.number 3
          = image_tag 'pict-reason-03.jpg',size:"300x300"
        %h3.list__text
          手数料
          %span 業界最安
        %p.list__description
          最大3%でお得に出品&購入！
  .middle__content
    .middle__content__inner    
      %h2.subtitle 会員数日本一位
      %p.text
        FURIMAは、フリマアプリで最も人気。
        %br/
        出品・購入回数も業界最多です！
        %br/
        ほしかったあの商品に出会えるかもしれません。
    .middle__content_btn 
      = link_to "" do
        = image_tag "App_Store_Badge.svg",size:"180x50"
      = link_to "" do
        = image_tag "google-play-badge.svg",size:"180x50"
  .concept 
    %h2.head FURIMAの特徴
    .items
      .item
        .item__img
        = image_tag "icon-01.png", size: "150x250"
        %h3.item__subtitle 簡単に売り買いできる
        %p.item__detail
        スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      .item
        .item__img
        = image_tag "icon-03.png", size: "150x250"
        %h3.item__subtitle 売上金は即日振込みに対応
        %p.item__detail
        午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      .item
        .item__img
        = image_tag "icon-04.png", size: "150x250"
        %h3.item__subtitle 様々な支払いに対応
        %p.item__detail
        お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  .recommendCategory
    %h2.head ピックアップカテゴリー
    .productBox
      .productHead
        = link_to ""
        %h3.title 新規投稿商品
      .productLists
        - @item.each do |item|
          .productList
            .productList--img
              = link_to (image_tag item.pictures[0].image.url,size:"185x189"), item_path(item.id)
              -if item.buyer_id == 1
                .productList--img__sold
                  
            %h3.name 
              = item.item_name
            .details
              %ul
                %li.price
                  = item.price 
                  円
                %li
                %i.fa.fa-star.likeIcon
                0
                %p
                  = item.delivery_charge_id
  .recommendBrand
    %h2.head ピックアップブランド
    .productBox
      .productHead
        = link_to ""
        %h3.title アーカイバ
      .productLists
        .productList
          = link_to "/products/3" do
            = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/13/a007.png"
          .productList--img
          %h3.name product3
          .details
            %ul
              %li 30000円
              %li
              %i.fa.fa-star.likeIcon
              0
              %p (税込)
        .productList
          = link_to "/products/2" do
            = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png"
          .productList--img
            %h3.name product2
            .details
              %ul
                %li 20000円
                %li
                %i.fa.fa-star.likeIcon
                0
                %p (税込)
        .productList
          = link_to "/products/1" do
            = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/7/a001.png"
          .productList--img
          %h3.name product1
          .details
            %ul
              %li 10000円
              %li
              %i.fa.fa-star.likeIcon
              0
              %p (税込)
  .footBar
    .inner
      %h2.inner__title だれでもかんたん、人生を変えるフリマアプリ
      %p.inner__text 今すぐ無料ダウンロード！
      .inner__icon
        = link_to "", class: "AppBtn" do
          = image_tag "App_Store_Badge.svg", size: "180x50"
        = link_to "", class: "GooBtn" do
          = image_tag "google-play-badge.svg", size: "180x50"

app/views/items/_purchase.html.haml
.purchase
  .purchase__header
    = image_tag 'logo.png'

  .purchase__title
    .purchase__home
      %p 購入内容の確認
  
  .purchase__main
    .purchase__information
      .purchase__box
        .purchase__image
          = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/7/a001.png"
        .purchase__description
          %p カレー(テスト)

      %hr.price-before
    .form
      .purchase__price
        .purchase__price-box
          %h3 支払い金額
          %h3 ¥1640

        .purchase__point-box
          = check_box_tag :check1
          = label_tag :check1, "ポイントを使用(所持ポイント：P0)"

      %hr.purchase__underline
      .purchase__method
        .purchase__top
          .purchase__top-box
            %p 支払い方法
            =link_to '変更する','#'
          %p 
          クレジットカード 
          %br 
          ************ 
          %br
          有効情報
          .purchase_cardLog
          = image_tag "/", height: "20", width: "32"

      %hr.purchase__underline
      .purchase__address
        .purchase__heading
          %p 配送先
          =link_to '変更する','#'
        %p 
        〒XXX-XXXX 
        %br 
        住所 
        %br
        名前

      %hr.purchase__underline
      .purchase__btn
        =link_to '購入する','#',class:"btn btn-default" 
      .purchase__app-btn
        アプリをお持ちでない方は以下よりインストール
        してご利用いただけます。
        .inner__icon
          = link_to "", class: "AppBtn" do
            = image_tag "App_Store_Badge.svg", size: "180x50"
          = link_to "", class: "GooBtn" do
            = image_tag "google-play-badge.svg", size: "180x50"

  .purchase__footer
    %ul
      %li
        =link_to 'プライバシーポリシー' , "#"
      %li 
        =link_to 'メルカリ利用規約' , "#"
      %li
        =link_to '特定商取引に関する表記' , "#" 
    .purchase__footer-logo
      = image_tag 'logo-white.png'
      %p © FURIMA,Inc.

app/views/items/done.html.haml
.container
  = render 'items/header'
  .purchase__main
    .purchase__main-top
      .purchase__main-top__message1
        = icon("fas", "clock")
        %p 発送をお待ちください
      .purchase__main-top__message2
        %p 出品者からの発送通知をお待ちください
    .purchase__main-middle
      %p 購入が完了しました
    .footerBox_back
      = link_to 'トップページに戻る',root_path, class: "backbutton"
  = render 'items/footer'

  

app/views/items/index.html.haml
.wrapper
= render 'header'
= render 'main'
= render 'footer'

app/views/items/purchase.html.haml
.purchase
  .purchase__header
    = image_tag 'logo.png'

  .purchase__title
    .purchase__home
      %p 購入内容の確認
  
  .purchase__main
    .purchase__information
      .purchase__box
        .purchase__image
        - @item.pictures.each do |picture|
          = image_tag "#{picture.image}"
        .purchase__description
          %p= @item.item_name

      %hr.price-before
    .form
      .purchase__price
        .purchase__price-box
          %h3 支払い金額
          %h3=@item.price

        .purchase__point-box
          = check_box_tag :check1
          = label_tag :check1, "ポイントを使用(所持ポイント：P0)"

      %hr.purchase__underline
      .purchase__method
        .purchase__top
          .purchase__top-box
            %p 支払い方法
            =link_to '変更する','#'
          %p 
          クレジットカード 
          - if @default_card_information.blank?
            %br/
          - else
            = "**** **** **** " + @default_card_information.last4
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
          %br
          有効情報
          .purchase_cardLog
          = image_tag "/", height: "20", width: "32"

      %hr.purchase__underline
      .purchase__address
        .purchase__heading
          %p 配送先
          =link_to '変更する','#'
        %p 
        〒 
        %br 
        住所 
        %br
        名前

      %hr.purchase__underline
      .purchase__btn
        =link_to '購入する',done_item_path, method: :post, class:"btn btn-default" 
      .purchase__app-btn
        アプリをお持ちでない方は以下よりインストール
        してご利用いただけます。
        .inner__icon
          = link_to "", class: "AppBtn" do
            = image_tag "App_Store_Badge.svg", size: "180x50"
          = link_to "", class: "GooBtn" do
            = image_tag "google-play-badge.svg", size: "180x50"

  .purchase__footer
    %ul
      %li
        =link_to 'プライバシーポリシー' , "#"
      %li 
        =link_to 'メルカリ利用規約' , "#"
      %li
        =link_to '特定商取引に関する表記' , "#" 
    .purchase__footer-logo
      = image_tag 'logo-white.png'
      %p © FURIMA,Inc.

app/views/items/show.html.haml
.wrapper
= render 'header'
.itemMain
  .showMain
    .contentLeftqq
      .contentRight
        .topContent
          .itemBox
            %h2.itemBox__name
              = @item.item_name

            .itemBox__body
              %ul
                %li
                  - @item.pictures.each do |picture|
                    = image_tag picture.image.url
                    
            .itemBox__price
              %span
                = "¥#{@item.price}"

              .itemBox__price-detail
                %span
                  (税込)
                %span
                  送料込み
            - if @item.buyer_id == 1
              .sold_out
                売り切れました
            %br
            .itemDetail
              = @item.discription
            .table
              %table
                %tbody
                  %tr
                    %th 出品者
                    %td 
                      = @item.user.nickname
                  %tr
                    %th カテゴリー
                    %td
                      = @item.category.parent.parent.name
                      %br
                      = @item.category.parent.name
                      %br
                      = @item.category.name
                  %tr
                    %th ブランド
                    %td
                      = @item.brand
                  %tr
                    %th 商品のサイズ
                    %td
                    = @item.size
                  %tr
                    %th 商品の状態
                    %td 
                      = @item.status.name
                  %tr
                    %th 配送料の負担
                    %td 
                      = @item.delivery_charge.name
                  %tr
                    %th 発送元の地域
                    %td
                      =link_to "#{@item.area.name}"
                  %tr
                    %th 発送日の目安
                    %td 
                      = @item.shipping_date.name
            .optionalArea
              %ul
                %li#likeBtn.optionalBtn.likeBtn
                  %i.fa.fa-star
                  お気に入り 0
              %ul.optional
                %li.optionalBtn
                  = link_to '' do
                    %i.fa.fa-flag
                    不適切な商品の通報
          .commentBox
            %ul.commentContents
            %form#new_comment.new_comment{"accept-charset" => "UTF-8", action: "#", method: "post"}
              %input{name: "utf8", type: "hidden", value: "✓"}
              %input{name: "authenticity_token", type: "hidden", value: "odOrqXT4yFlepYJilzx8Evj1sY2mzm24tcTbB93bppoPxV5gfR7y8EmB3NimnRyiCl4Y40D+zbLhWoYbGIaq9A=="}/
              %textarea#comment_body{name: "comment[body]", required: "required"}
              %p.noticeMsg
                相手のことを考え丁寧なコメントを心がけましょう。
                %br/
                不快な言葉遣いなどは利用制限や退会処分となることがあります。
              %br/
              %button.commentBtn{name: "button", type: "submit"}
                %i.fa.fa-comment
                コメントする 
            - if user_signed_in? && current_user.id == @item.user_id
              = link_to "この商品を削除する",item_path(@item.id), method: :delete, class: "destroyBtn"
              = link_to "商品の編集",edit_item_path(@item),class:"editBtn"
            - if user_signed_in? && current_user.id != @item.user_id && @item.buyer_id != 1
              = link_to "購入画面に進む",purchase_item_path(@item.id),class:"purchaseBtn"
        %ul.links
          %li
            = link_to '' do
              %i.fa.fa-angle-left
              %span
              前の商品
          %li
            = link_to '' do
              %span 後ろの商品
              %i.fa.fa-angle-right
        .relatedItems
          = link_to 'ベビー・キッズをもっと見る'
          .productLists
.wrapper
= render 'footer'