config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items do
    member do
      get 'purchase',to: 'items#purchase'
      post 'done',to: 'items#done'
     end
  #Ajaxで動くアクションのルート
  collection do
    get 'get_category_children', defaults: { format: 'json' }
    get 'get_category_grandchildren', defaults: { format: 'json' }
  end
  end 
  resources :users, only: [:edit, :update, :show] do
    resources :addresses, only: [:new, :create, :edit, :update]
  end

  resources :cards, only: [:index,:new,:show] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'buy', to: 'cards#buy'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
      {id: 1, name:'北海道'}, 
      {id: 2, name:'青森県'},
      {id: 3, name:'岩手県'}, 
      {id: 4, name:'宮城県'}, 
      {id: 5, name:'秋田県'}, 
      {id: 6, name:'山形県'}, 
      {id: 7, name:'福島県'}, 
      {id: 8, name:'茨城県'}, 
      {id: 9, name:'栃木県'}, 
      {id: 10, name:'群馬県'}, 
      {id: 11, name:'埼玉県'}, 
      {id: 12, name:'千葉県'}, 
      {id: 13, name:'東京都'}, 
      {id: 14, name:'神奈川県'}, 
      {id: 15, name:'新潟県'}, 
      {id: 16, name:'富山県'}, 
      {id: 17, name:'石川県'}, 
      {id: 18, name:'福井県'}, 
      {id: 19, name:'山梨県'}, 
      {id: 20, name:'長野県'}, 
      {id: 21, name:'岐阜県'}, 
      {id: 22, name:'静岡県'}, 
      {id: 23, name:'愛知県'}, 
      {id: 24, name:'三重県'}, 
      {id: 25, name:'滋賀県'}, 
      {id: 26, name:'京都府'}, 
      {id: 27, name:'大阪府'}, 
      {id: 28, name:'兵庫県'}, 
      {id: 29, name:'奈良県'}, 
      {id: 30, name:'和歌山県'}, 
      {id: 31, name:'鳥取県'}, 
      {id: 32, name:'島根県'}, 
      {id: 33, name:'岡山県'}, 
      {id: 34, name:'広島県'}, 
      {id: 35, name:'山口県'}, 
      {id: 36, name:'徳島県'}, 
      {id: 37, name:'香川県'}, 
      {id: 38, name:'愛媛県'}, 
      {id: 39, name:'高知県'}, 
      {id: 40, name:'福岡県'}, 
      {id: 41, name:'佐賀県'}, 
      {id: 42, name:'長崎県'}, 
      {id: 43, name:'熊本県'}, 
      {id: 44, name:'大分県'}, 
      {id: 45, name:'宮崎県'}, 
      {id: 46, name:'鹿児島県'}, 
      {id: 47, name:'沖縄県'}, 
  ]
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
end

app/models/delivery_charge.rb
class DeliveryCharge < ActiveHash::Base
  self.data = [
      {id: 1, name: '送料込み(出品者負担)'},
      {id: 2, name: '着払い(購入者負担)'},
  ]
end

app/models/item.rb
class Item < ApplicationRecord

  #active_hash
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :status
  belongs_to_active_hash :delivery_charge
  belongs_to_active_hash :shipping_date
  belongs_to_active_hash :area


  #Association
  belongs_to :user
  has_many :comments
  has_many :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures, allow_destroy: true
  belongs_to :category

  #validation
  validates :price,:status,:delivery_charge_id,:area_id,:shipping_date_id, presence: true
  validates :item_name, presence: true, length: {maximum: 40}
  validates :discription, presence: true, length: {maximum: 1000}

  validates_associated :pictures
  validates :pictures, presence: true
  
  
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader

  #Association
  belongs_to :item
  validates :image, presence: true
end

app/models/shipping_date.rb
class ShippingDate < ActiveHash::Base
  self.data = [
      {id: 1, name: '1~2日で発送'},
      {id: 2, name: '2~3日で発送'},
      {id: 3, name: '4~7日で発送'},
  ]
end

app/models/shipping_method.rb
class ShippingMethod < ActiveHash::Base
  self.data = [
    {id: 1, name: "ゆうメール"},
    {id: 2, name: "ゆうパケット"},
    {id: 3, name: "クリックポスト"},
    {id: 4, name: "ゆうパック"},
    {id: 5, name: "宅急便"},
    {id: 6, name: "普通郵便"},
    {id: 7, name: "レターパック"},
    {id: 8, name: "ゆうゆうフリマ便"},
    {id: 9, name: "らくらくフリマ便"},
  ]
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
      {id: 1, name: '新品、未使用'},
      {id: 2, name: '未使用に近い'},
      {id: 3, name: '目立った傷や汚れなし'},
      {id: 4, name: 'やや傷や汚れあり'},
      {id: 5, name: '傷や汚れあり'},
      {id: 6, name: '全体的に状態が悪い'},
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader

  has_many :items
  validates :nickname, :first_name, :last_name, :first_name_kana, :last_name_kana, :birthday, presence: true
  validates :profile, length: { maximum: 250 }

  has_many :cards 
  has_one :address
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  require "payjp"

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to card_path(card) if card.exists?
  end

  def pay
    Payjp.api_key = "sk_test_1547c1078a795141e2ee8623"
    if params['payjp-token'].blank?
      redirect_to new_card_path
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: 'show'
      else
        redirect_to pay_cards_path
      end
    end
  end

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to card_path(card) if card.exists?
  end

  def pay
    Payjp.api_key = "sk_test_1547c1078a795141e2ee8623"
    if params['payjp-token'].blank?
      redirect_to new_card_path
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to card_path(@card)
      else
        redirect_to pay_cards_path(@card)
      end
    end
  end

  def delete
    card = Card.find_by(user_id: current_user.id)
    if card.present?
      Payjp.api_key = "sk_test_1547c1078a795141e2ee8623"
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
      redirect_to new_card_path
    end
  end

  def show
    @card = Card.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to new_card_path(@user)
    else
      Payjp.api_key = "sk_test_1547c1078a795141e2ee8623"
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_card-leftside.html.haml
.side
  .mypage-nav
    .mypage-nav__list          
      %li.mypage-nav__list-item
        マイページ
      %li.mypage-nav__list-item
        お知らせ
      %li.mypage-nav__list-item
        やることリスト
      %li.mypage-nav__list-item
        いいね！一覧
      %li.mypage-nav__list-item
        出品する
      %li.mypage-nav__list-item
        出品した商品-出品中
      %li.mypage-nav__list-item
        出品した商品-取引中
      %li.mypage-nav__list-item
        出品した商品-売却済み
      %li.mypage-nav__list-item
        購入した商品-取引中
      %li.mypage-nav__list-item
        購入した商品-過去の取引
      %li.mypage-nav__list-item
        ニュース一覧
      %li.mypage-nav__list-item
        評価一覧
      %li.mypage-nav__list-item
        ガイド
      %li.mypage-nav__list-item
        お問い合わせ

    .mypage-nav__head
      ペイメント
    .mypage-nav__list
      %li.mypage-nav__list-item
        売上・振込申請

      %li.mypage-nav__list-item
        ポイント
    

    
    .mypage-nav__head
      設定
    .mypage-nav__list
      %li.mypage-nav__list-item
        プロフィール
    
    .mypage-nav__list
      %li.mypage-nav__list-item
        -# もしユーザーがすでに発送元・お届け先住所(address)を登録済であれば編集画面へ
        -# でなければ新規登録画面へ
        -# - if @user.address.present?
        -#  = link_to "発送元・お届け先住所変更", edit_user_address_path(@user)
        -# - else
        = link_to "発送元・お届け先住所変更", "#"
    .mypage-nav__list
      %li.mypage-nav__list-item
        = link_to "支払い方法",   "#"
      
    .mypage-nav__list
      %li.mypage-nav__list-item
        メール/パスワード
      
    .mypage-nav__list
      %li.mypage-nav__list-item
        本人情報
      
    .mypage-nav__list
      %li.mypage-nav__list-item
        電話番号の確認
      
    .mypage-nav__list
      %li.mypage-nav__list-item
        ログアウト

app/views/cards/_cards.html.haml
.card-box
  %div.card-box__header 支払い方法
  %div.card-box__list クレジットカード一覧
  %div.card-box__btn
    = link_to "クレジットカードを追加する"
  %div.card-box__underline
  %div.card-box__payment お支払い方法について

app/views/cards/_creditcard-form.html.haml
= form_with model: @card,url: pay_cards_path, method: :post,id: 'charge-form',class: "card-form",html: { name: 'inputForm' } do |f|
  .card-form__header クレジットカード登録
  .card-form__number
    .card-form__number--top
      = f.label "カード番号"
      %span.required 必須
      %br
    .card-form__number__center
      = f.text_field :name, placeholder: "半角数字のみ", class: "input-field",id: "card-number", maxlength: "16"
    %ul.card-form__number__bottom
      %li 
        = image_tag "visa.png", height: "20", width: "34"
      %li 
        = image_tag "master.png", height: "20", width: "34"
      %li 
        = image_tag "jcb.png", height: "20", width: "32"
      %li 
        = image_tag "american.png", height: "20", width: "21"
      %li 
        = image_tag "saison.png", height: "20", width: "30"
      %li 
        = image_tag "discover.png", height: "20", width: "32"
      %li 
        = image_tag "dinersclub.png", height: "20", width: "32"
  .card-form__expiration
    .card-form__expiration--top
      = f.label "有効期限"
      %span.required 必須
      %br
    .card-form__expiration__center
      .card-form__expiration__center--month
        = f.select :exp_month, [["01", 1],["02", 2],["03", 3],["04", 4],["05", 5],["06", 6],["07", 7],["08", 8],["09", 9],["10", 10],["11", 11],["12", 12]], {}, {class: "select-form",id:"exp_month"}
        %ladel
          = icon("fab", "chevron-down")
          %span 月
      .card-form__expiration__center--year
        = f.select :exp_year, [["20", 2020],["21", 2021],["22", 2022],["23", 2023],["24", 2024],["25", 2025],["26", 2026],["27", 2027],["28", 2028],["29", 29],["30", 2030]], {}, {class: "select-form",id:"exp_year"}
        %ladel
          = icon("fab", "chevron-down")
          %span 年
  .card-form__security
    .card-form__security--top
      = f.label "セキュリティコード"
      %span.required 必須
      %br
    .card-form__security__center
      = f.text_field :cvc, placeholder: "カード背面４桁もしくは３桁の番号", class: "input-field",id:"cvc"
    .card-form__security__bottom 
      = icon("fas", "question-circle") 
      カード裏面の番号とは？
    .card-form__security__info
      カードの裏面をご参照ください
      -# = image_tag ("seq-card.png"), class: "card-info-img"
  .card-form__btn#card_token
    = f.submit "追加する", class: "submit-btn", id: "token_submit"

app/views/cards/_creditcard-list.html.haml
.card-box
  .card-box__header 支払い方法
  .card-box__list
    %h3 クレジットカード一覧
    - if @card.present?
      %p.creditcard-info__number
        = "**** **** **** " + @default_card_information.last4
      %br
      %p.creditcard-info__period 
      - exp_month = @default_card_information.exp_month.to_s
      - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
      = exp_month + " / " + exp_year
      = form_tag(delete_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
        %input{ type: "hidden", name: "card_id", value: "" }
        %button 削除する
    - else 
      .card-box__new-card
      = link_to new_card_path do
        %i.far.fa-credit-card
        クレジットカードを追加する
  .card-box__underline
  .card-box__payment お支払い方法について

app/views/cards/new.html.haml
.container
  = render 'items/header'
  .mypage_main
    = render "creditcard-form"
    = render "card-leftside"
  = render 'items/footer'

app/views/cards/show.html.haml
.container
  = render 'items/header'
  .mypage_main
    = render "card-leftside"
    = render "creditcard-list"
  = render 'items/footer'